---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hocs-casework
  labels:
    version: {{.VERSION}}
  annotations:
    downscaler/uptime: {{.UPTIME_PERIOD}}
spec:
  replicas: {{.MIN_REPLICAS}}
  selector:
    matchLabels:
      name: hocs-casework
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hocs-casework
        role: hocs-backend
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
        - name: registry-credentials
      initContainers:
        - name: truststore
          image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:v0.0.9
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --command=/usr/bin/create-keystore.sh /certs/tls.pem /certs/tls-key.pem /etc/ssl/certs/acp-root.crt
            - --domain=hocs-casework.${KUBE_NAMESPACE}.svc.cluster.local
            - --domain=localhost
            - --onetime=true
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: keystore
              mountPath: /etc/keystore
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            limits:
              memory: 96Mi
              cpu: 900m
            requests:
              memory: 96Mi
              cpu: 300m

      containers:
        - name: hocs-casework
          image: quay.io/ukhomeofficedigital/hocs-casework:{{.VERSION}}
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          envFrom:
            - configMapRef:
                name: hocs-queue-config
          env:
            - name: JAVA_OPTS
              value: '-Xms1280m -Xmx1280m -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks -Dhttps.proxyHost=hocs-outbound-proxy.{{.KUBE_NAMESPACE}}.svc.cluster.local -Dhttps.proxyPort=31290 -Dhttp.nonProxyHosts=*.{{.KUBE_NAMESPACE}}.svc.cluster.local'
            - name: JDK_KEYSTORE_FILE
              value: '/etc/keystore/keystore.jks'
            - name: SERVER_PORT
              value: '8443'
            - name: SPRING_PROFILES_ACTIVE
              value: 'sns, sqs, tls'
            - name: HOCS_AUDIT_SERVICE
              value: 'https://hocs-audit.{{.KUBE_NAMESPACE}}.svc.cluster.local'
            - name: HOCS_INFO_SERVICE
              value: 'https://hocs-info-service.{{.KUBE_NAMESPACE}}.svc.cluster.local'
            - name: HOCS_SEARCH_SERVICE
              value: 'https://hocs-search.{{.KUBE_NAMESPACE}}.svc.cluster.local'
            - name: HOCS_DOCUMENT_SERVICE
              value: 'https://hocs-docs.{{.KUBE_NAMESPACE}}.svc.cluster.local'
            - name: HOCS_BASICAUTH
              valueFrom:
                secretKeyRef:
                  name: ui-casework-creds
                  key: plaintext
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-casework-rds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-casework-rds
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-casework-rds
                  key: name
            - name: DB_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-casework-rds
                  key: schema_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-casework-rds
                  key: user_name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-casework-rds
                  key: password
            - name: AWS_SNS_AUDIT_SEARCH_TOPIC_NAME
              value: {{.KUBE_NAMESPACE}}-sns
            - name: AWS_SNS_AUDIT_SEARCH_ACCOUNT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-audit-sqs
                  key: access_key_id
            - name: AWS_SNS_AUDIT_SEARCH_ACCOUNT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-audit-sqs
                  key: secret_access_key
            - name: AWS_SNS_AUDIT_SEARCH_ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: hocs-queue-config
                  key: AWS_ACCOUNT_ID
            - name: AUDITING_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AUDITING_DEPLOYMENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AWS_SQS_NOTIFY_URL
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-notify-sqs
                  key: sqs_queue_url
            - name: AWS_SQS_NOTIFY_ACCOUNT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-notify-sqs
                  key: access_key_id
            - name: AWS_SQS_NOTIFY_ACCOUNT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-notify-sqs
                  key: secret_access_key
          resources:
            limits:
              cpu: 2000m
              memory: 2204Mi
            requests:
              cpu: 350m
              memory: 2204Mi
          ports:
            - name: https
              containerPort: 8443
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              scheme: HTTPS
              port: https
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              scheme: HTTPS
              port: https
              httpHeaders:
                - name: X-probe
                  value: kubelet
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              scheme: HTTPS
              port: https
              httpHeaders:
                - name: X-probe
                  value: kubelet
            periodSeconds: 2
          volumeMounts:
            - mountPath: /etc/keystore
              name: keystore
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 20" ]
      volumes:
        - name: keystore
          emptyDir:
            medium: "Memory"
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
        - name: secrets
          emptyDir:
            medium: "Memory"
        - name: auth-secrets
          secret:
            secretName: ui-casework-creds
