---
hocs-generic-service:
  nameOverride: hocs-casework

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-casework
    resources:
      limits:
        memory: 1536Mi
      requests:
        memory: 1536Mi
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=70
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'sqs, sns'
      auditService: https://hocs-audit.{{ .Release.Namespace }}.svc.cluster.local
      infoService: https://hocs-info-service.{{ .Release.Namespace }}.svc.cluster.local
      searchService: https://hocs-search.{{ .Release.Namespace }}.svc.cluster.local
      docsService: https://hocs-docs.{{ .Release.Namespace }}.svc.cluster.local
      # The 'real' migration values need to be in a secret
      migrationUserId: cms
      migrationUserName: migration
      migrationGroup: cms
