---
hocs-generic-service:

  deployment:
    annotations:
      downscaler/downtime: "Mon-Sun 00:00-07:50 Europe/London,Mon-Sun 18:05-24:00 Europe/London"

  truststore:
    resources:
      requests:
        cpu: 50m

  app:
    env:
      searchService: https://hocs-search-opensearch.{{ .Release.Namespace }}.svc.cluster.local
    resources:
      limits:
        memory: 768Mi
      requests:
        cpu: 50m
        memory: 768Mi
