---
hocs-backend-service:
  minReplicas: 1
  maxReplicas: 1

  deploymentAnnotations:
    downscaler/uptime: "Mon-Sun 07:55-18:05 Europe/London"

  app:
    resources:
      limits:
        cpu: 300m
        memory: 768Mi
      requests:
        cpu: 100m
        memory: 768Mi
