package uk.gov.digital.ho.hocs.casework.client.auditclient;

public enum EventType {
    STAGE_ALLOCATED_TO_USER,
    STAGE_ALLOCATED_TO_TEAM,
    STAGE_COMPLETED,
    STAGE_CREATED,
    STAGE_RECREATED,
    STAGE_UNALLOCATED_FROM_USER,
    CASE_CREATED,
    CASE_UPDATED,
    CASE_VIEWED,
    CASE_COMPLETED,
    CASE_DELETED,
    CASE_SUMMARY_VIEWED,
    STANDARD_LINE_VIEWED,
    TEMPLATE_VIEWED,
    CASE_NOTE_CREATED,
    CASE_NOTES_VIEWED,
    CASE_NOTE_VIEWED,
    CORRESPONDENT_CREATED,
    CORRESPONDENT_DELETED,
    CASE_TOPIC_CREATED,
    CASE_TOPIC_DELETED,
    DOCUMENT_CREATED,
    DOCUMENT_DELETED
}